### ISSUE TITLE
[bug]Markdown mode is not automatically starting when I open .md files .

### ISSUE THREAD

**Issue by bommbo** [a-schaefers/spartan-emacs#8] opened 2024-05-26 02:38 UTC
Configuration:
```
(use-package markdown-mode
  :straight t)
```
I must put this configuration in spartan.el file to fix this.

**Comment by a-schaefers** [comment] 2024-05-26 05:45
There's a markdown layer in `spartan-library/spartan-markdown.md` and if you drop it in to `spartan.d` and close/reopen Emacs, then open some `foo.md` file you will be in the major mode of markdown.

Tested, definitely works.

So, there must be some elisp error somewhere else in one of your spartan.d files that is causing it to stop loading the remaining files. Elisp bails out if there is an error.

**Comment by a-schaefers** [comment] 2024-05-26 05:46
cannot reproduce

**Comment by a-schaefers** [comment] 2024-05-26 05:47
I recommend turning on toggle debug on error early in init.el temporarily and finding where the bug is

**Comment by bommbo** [comment] 2024-05-26 06:51
Open the terminal and type emacs filename.md to open a Markdown file with Emacs.
eg:
```
emacs test.md 
```
or
```
emacs -nw test.md
```

**Comment by a-schaefers** [comment] 2024-05-26 06:55
[Uploading Screencast from 2024-05-26 00-54-47.webm…]()

**Comment by a-schaefers** [comment] 2024-05-26 06:57
https://imgur.com/a/wNuqehx

cannot reproduce.

**Comment by bommbo** [comment] 2024-05-26 07:02
wait. I can give you video.

**Comment by a-schaefers** [comment] 2024-05-26 07:05
Remove all your other files from spartan.d, just leaving spartan-markdown.el alone in the directory - it should work. You have a bug somewhere in spartan.d or in spartan.el or some other change you might have made somewhere. Freshly clone the project and just add spartan-markdown.el to spartan.d, it will work. When you have an elisp e.g. syntax error somewhere else, it causes the entire Emacs load process to halt, leaving things unloaded, e.g. markdown. This is the most likely case for you. This layer is tested on everything by now, macos, debian, arch linux, ubuntu, etc.

**Comment by bommbo** [comment] 2024-05-26 07:07
Trust me. you should type "emacs file" first. not open emacs and then open markdown file.

**Comment by bommbo** [comment] 2024-05-26 07:10
https://imgur.com/a/cttpeGS

**Comment by a-schaefers** [comment] 2024-05-26 07:11
ok weird I see what you mean

**Comment by a-schaefers** [comment] 2024-05-26 07:14
i have a fix incoming, it's not just markdown mode when opening this method - it's pretty much everything

**Comment by a-schaefers** [comment] 2024-05-26 07:14
I mean why would you close Emacs and open file directly with it? JK

**Comment by a-schaefers** [comment] 2024-05-26 07:15
If we change init.el's loading of spartan.d to use after-init-hook instead of emacs-startup-hook, problems go away

**Comment by bommbo** [comment] 2024-05-26 07:15
I like terminal...

**Closed** 2024-05-26 07:18 UTC

**Comment by a-schaefers** [comment] 2024-05-26 07:19
Go ahead and check out https://github.com/a-schaefers/spartan-emacs/commit/1fc6f1e5c64fd2dc972ada34ae9fd157217ad5a5 and pull it in to test, I think this is the right fix.

I never work with Emacs this way, personally, so I've never hit this issue, but it's pretty harmless to use after-init-hook. I prior used emacs-startup-hook because it is AFAIK basically the latest hook available and I wanted to give users total ability to customize any of the defaults and have the "final say"

**Comment by a-schaefers** [comment] 2024-05-26 07:24
Let me know how it goes, thanks for your report, and sorry for assuming you had a syntax error.

**Comment by bommbo** [comment] 2024-05-26 07:24
Thx,Bro. I like your Emacs framework. But I need to transfer past configurations, which might cause some issues, so I frequently ask questions.

**Comment by a-schaefers** [comment] 2024-05-26 07:25
Keep reporting, it'll make it better the more people who chime in their experience. And I'm glad you like it.
