### ISSUE TITLE
[bug] Savehist-mode 

### ISSUE THREAD

**Issue by bommbo** [a-schaefers/spartan-emacs#6] opened 2024-05-24 14:00 UTC
Same issue like this :
https://www.reddit.com/r/emacs/comments/11w2d1e/savehistmode/

**Comment by a-schaefers** [comment] 2024-05-24 19:57
I am unable to reproduce locally, closing and reopening, and looking at M-x does show the last minibuffer commands used from the last session.

C-h v savehist-file shows,

savehist-file is a variable defined in ‘savehist.el’.

Its value is "~/.emacs.d/history"

and the file exists in my local setup.

Can you provide any more information about any modifications you've made to the defaults?

**Comment by a-schaefers** [comment] 2024-05-24 20:43
Unless you're talking about the M-r reverse search feature in shell-mode, because that definitely has never persisted and has always annoyed me. Until now c0161d8 - FIXED.

**Comment by bommbo** [comment] 2024-05-25 01:44
https://streamable.com/8q3ce2

**Comment by a-schaefers** [comment] 2024-05-25 23:59
Bug confirmed.

`~/.emacs.d/spartan-layers/spartan-vertico.el`

The addon code for fuzzy completion is causing the issue

```emacs
;; fuzz

(use-package prescient
  :straight t)

(use-package vertico-prescient
  :after (vertico prescient)
  :straight t
  :init (vertico-prescient-mode 1))
```

When commented out, we lose fuzzy matching, but savehist works again. Fuzzy matching has been very useful so we'll need to find out how to make savehist and vertico-prescient play nicely together.

**Closed** 2024-05-26 00:14 UTC

**Comment by a-schaefers** [comment] 2024-05-26 00:18
Per the doc page for prescient,

prescient-save-file: Where to save statistics that are persisted between Emacs sessions when prescient-persist-mode is active. The default value follows the conventions of [no-littering](https://github.com/emacscollective/no-littering).

https://github.com/radian-software/prescient.el

While it's unfortunate that savehist isn't used by prescient (vertico has no problem using savehist when it's alone), when prescient fuzzy matching is added in to the mix with vertico, savehist is ignored in the way it is displaying the results in M-x, C-x C-f, etc. 

I consider fuzzy matching too useful to give up and we're going to piss off a lot of users if we just suddenly remove fuzzyness, so instead of doing that, we can just turn prescient's additional method to save the minibuffer history. Seems to work fine for me so I pushed up the change.

Thanks for the report.

**Comment by bommbo** [comment] 2024-05-26 02:43
I prefer using orderless and have created a separate configuration.

**Comment by a-schaefers** [comment] 2024-05-26 07:26
If orderless is better, open a PR with a forked branch in the future, maybe we can consider merging it in, or making it some kind of option. I'll try your config if you PR. But I imagine you're probably busy, so maybe just keep it in the back pocket for us.
